// packages/react-app/src/app/app.tsx
import { MyComponent, BongaButton } from '@bongaui/core-components-react';

export function App() {
  return (
    <div>
      <h2>El componente de sebas</h2>
      <MyComponent first="First name" last="Last name" />
      <h2>Bonga Button</h2>
      <BongaButton color="primary">Primary</BongaButton>
      <BongaButton color="secondary">Secondary</BongaButton>
      <BongaButton color="tertiary">Tertiary</BongaButton>
      <BongaButton>Default</BongaButton>

      <h2>Block Width</h2>
      <BongaButton color="primary" expand="block">
        A block button
      </BongaButton>

      <h2>Full Width</h2>
      <BongaButton color="secondary" expand="full">
        A full-width button
      </BongaButton>
    </div>
  );
}

export default App;

// packages/angular-app/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'bongaui-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  title = 'angular-app';
}

<h2>Estamos en Angular y este es el componente de sebas</h2>
<my-component first="First name" last="Last name"></my-component>
<h2>Bonga Button</h2>
<bonga-button color="primary">Primary</bonga-button>
<bonga-button color="secondary">Secondary</bonga-button>
<bonga-button color="tertiary">Tertiary</bonga-button>
<bonga-button>Default</bonga-button>

<h2>Block Width</h2>
<bonga-button color="primary" expand="block">A block button</bonga-button>

<h2>Full Width</h2>
<bonga-button color="secondary" expand="full">A full-width button</bonga-button>
